### ISSUE TITLE
cannot connect to EWS server with recent flatpak versions (eg 3.48.1)

### ISSUE THREAD

**Issue by monperrus** [flathub/org.gnome.Evolution#107]
I cannot connect anymore to the Exchange / EWS server. 

Invalid hypotheses:
* <s>My Exchange server expects NTLM authentication, which is based on MD4 and MD4 is forbidden.</s>
* <s>It seems that this is due to a recent [Ubuntu upgrade](https://ubuntu.com/blog/whats-new-in-security-for-ubuntu-22-04-lts) of [OpenSSL to v3](https://wiki.openssl.org/index.php/OpenSSL_3.0) dropping support for MD4.</s>

**Comment by monperrus** [comment]
> because the Exchange connector (evoltuion-ews) uses libsoup for connection, which uses GLib's gio part, which related on glib-networking, which can be configured to use either GnuTLS or OpenSSL

super interesting thanks @mcrha 

related resources for future debug
[Merge OpenSSL backend into glib-networking (#40) · Issues](https://gitlab.gnome.org/GNOME/glib-networking/-/issues/40)
[Support OpenSSL 3.0 (#170) · Issues · GNOME / glib-networking](https://gitlab.gnome.org/GNOME/glib-networking/-/issues/170)

**Comment by monperrus** [comment]
Progress report:

- Tried again today, Evolution flatpak is still broken, cannot connect to my employer EWS server because of unsupported NTLM
- `update-crypto-policies --set LEGACY` does not fix the issue
- found related resources, mentioning libsoup:
  - Support for NTLMv2 Authentication with recent work by @mcrha https://bugzilla.redhat.com/show_bug.cgi?id=1938011
  - NTLMv2 in Evolution https://gitlab.gnome.org/GNOME/evolution-ews/-/issues/38
  - for the record I have libsoup 2.74.2-3

Open questions:

- how to know whether the Exchange server supports NTLMv1, NTLMv2 or both?
- how to force Evolution using NTLMv1 or NTLMv2? (the UI only says NTLM)
- how to know whether glib-networking is configured with OpenSSL or GnuTLS on my machine?

Thanks!

**Comment by mcrha** [comment]
> Tried again today, Evolution flatpak is still broken, cannot connect to my employer EWS server because of unsupported NTLM

It's not unsupported NTLM, it's the use of the insecure MD4 by the NTLM. There's nothing broken anywhere in the code. See my first reply above.

> * `update-crypto-policies --set LEGACY` does not fix the issue

Hmm, when talking about it, I'm wondering whether it catches also Flatpak apps. In any case, such changes require restart of the application, or the whole system. Restarting Flatpak evolution is tricky, due to left background processes running. Did you restart the processes, or the machine, after the change?

> * Support for NTLMv2 Authentication with recent work by @mcrha https://bugzilla.redhat.com/show_bug.cgi?id=1938011

That's RHEL 8.3, it has nothing to do with your system. It's ancient.

> * for the record I have libsoup 2.74.2-3

If you mean in your system, then it's not what the Flatpak uses. Flatpak bundles its own libraries (which is the reason why it can work on old/ancient systems too).

> how to know whether the Exchange server supports NTLMv1, NTLMv2 or both?

No idea, I'm sorry. It's the protocol thing. You may realize based on the error message being returned, I'd expect.

> how to force Evolution using NTLMv1 or NTLMv2? (the UI only says NTLM)

The decision is up to the server, not to the client, as far as I can tell.

> how to know whether glib-networking is configured with OpenSSL or GnuTLS on my machine?

By finding the build scripts. Use of `ldd` is a way, but it can be tricky, due to other dependencies bringing in either of the two libraries.

Opening terminal within the sandbox (`flatpak run --command=sh org.gnome.Evolution`), I see there is `libgiognutls.so` in `/usr/lib/x86_64-linux-gnu/gio/modules/`, thus the Flatpak builds with GnuTLS. According to `/usr/manifest.json` there is built `libsoup 3.4.1`.  I do not see `update-crypto-policies` in the sandbox, from which I suppose the Flatpak inherits the settings from the system, which makes perfect sense to me.

**Comment by monperrus** [comment]
> Did you restart the processes, or the machine, after the change?

the whole machine.

thanks for the additional pointers, I'll further debug.

**Comment by mcrha** [comment]
That's odd. I'm wondering whether the `update-crypto-policies` even worked. The `update-crypto-policies --show` may show.

I hope I did not overlook it, but I do not see an exact error message you see in the Evolution. Does it mention MD4, or it's just a guess from your side, please?

Could you try running:

```
   curl --verbose https://your.exchange.server.com/EWS/Exchange.asmx --ntlm --user "USER:PASSWORD"
```

whether it'll fail the same way as Evolution, please? Add argument ` --insecure`, in case your server uses a self-signed certificate. The request should end with `200 OK`, not with `401 Unauthorized`, even the returned content will contain an error message. My idea is to try to connect and authenticate with NTLM towards your server with a different application.

Note that running the `curl` command in the host system terminal and inside the Flatpak sandbox (`flatpak run --command=sh org.gnome.Evolution`) can produce different results.

**Comment by monperrus** [comment]
> ± update-crypto-policies --show

LEGACY

> `curl --verbose https://your.exchange.server.com/EWS/Exchange.asmx --ntlm --user "USER:PASSWORD"`

This works both in the host and in the flatpak sandbox. My understanding is that curl depends on openssl, and I was already able to accept md4 with changing `/etc/ssl/openssl.cnf`.

If this is correct, the problem comes from gnutls. On the host, the only config I see is `/etc/crypto-policies/back-ends/gnutls.config`

    SYSTEM=NONE:+MAC-ALL:+MD5:+GROUP-ALL:+SIGN-ALL:-SIGN-RSA-MD5:+SIGN-RSA-SHA1:+SIGN-DSA-SHA1:%VERIFY_ALLOW_SIGN_WITH_SHA1:+CIPHER-ALL:-CAMELLIA-256-GCM:-CAMELLIA-128-GCM:-CAMELLIA-256-CBC:-CAMELLIA-128-CBC:+3DES-CBC:+ARCFOUR-128:+ECDHE-RSA:+ECDHE-ECDSA:+RSA:+DHE-RSA:+DHE-DSS:+VERS-ALL:-VERS-DTLS0.9:-VERS-SSL3.0:+COMP-NULL:%PROFILE_LOW

I tried `+MD4:` without success.

**Comment by mcrha** [comment]
Those configs need to be applied somehow, if I'm not mistaken. You are right the `curl` uses OpenSSL. The `wget` uses GnuTLS.

Again, what is the exact error message you see in the Evolution, please?

**Comment by monperrus** [comment]
With `EWS_DEBUG=2  flatpak run org.gnome.Evolution`, only HTTP 401s, no clear error message. Sent you the logs via email.

**Comment by mcrha** [comment]
Aha, I see, the server does not provide any useful information why it rejected the `Authorization` the evolution-ews sends to it. It's really hard to debug what gone wrong. The log shows there is used HTTP/2, maybe switch to the HTTP/1, which can be done in the EWS account Properties->Receiving Options tab->Always connect with HTTP/1 option. I do not know whether it'll help, possibly not.

You mentioned it worked before certain update of your system. Maybe the Evolution itself also updated, together with its dependencies (newer runtime version). It's easy to downgrade Evolution in flatpak. Maybe if we knew what change caused it, then it'll help to debug it.

The server advertises it can do `Basic` and `Negotiate` (aka Kerberos) authentications. Did you try to use it instead of the NTLM? As a workaround.

By the way, I suppose your host system Evolution is older than 3.48.x. Can it connect to your server?

**Comment by monperrus** [comment]
> The server advertises it can do Basic and Negotiate (aka Kerberos) authentications. Did you try to use it instead of the NTLM?

Tried, it does not work.

> By the way, I suppose your host system Evolution is older than 3.48.x. Can it connect to your server?

Yes, my host Evolution 3.44 works (Ubuntu build).

> Maybe if we knew what change caused it, then it'll help to debug it.

The problem happened when I first reported [the issue](https://gitlab.gnome.org/GNOME/evolution/-/issues/2200) (Dec 17 2022). So it's caused by a flatpak update  that happened perhaps in the Oct-Dec 22 range.

> The log shows there is used HTTP/2,

Interesting.
* flatpak evolution does not show option "Properties->Receiving Options tab->Always connect with HTTP/1"
* you write ["Evolution 3.44.x, which uses libsoup2, which doesn't know about HTTP/2, it's HTTP/1 (/1.1) only."](https://gitlab.gnome.org/GNOME/evolution/-/issues/2159). And I'm also successfully running 3.44 on the host. Coincidence?

**Comment by mcrha** [comment]
> So it's caused by a flatpak update that happened perhaps in the Oct-Dec 22 range.

According to `flatpak remote-info flathub org.gnome.Evolution// --log | more` the changes in question are:

```
   Subject: Update to Evo 3.46.3 (673fbe92)
      Date: 2023-01-09 17:39:05 +0000

   Subject: Update to Evo 3.46.2 (dc7b1ce6)
      Date: 2022-12-06 15:50:17 +0000

   Subject: Removing gcr (a219326b)
      Date: 2022-10-31 16:05:57 +0000
```

> flatpak evolution does not show option "Properties->Receiving Options tab->Always connect with HTTP/1"

You did not update to the latest version then, because I checked the option exists there before writing it in my previous comment.

What does `flatpak info org.gnome.Evolution` return for you, please?

Does anything change after `flatpak update`? Supposing it'll update Evolution and at least some runtimes. Make sure you'll also run `flatpak kill org.gnome.Evolution`, to have any leftover background processes closed and the new run of the Evolution will start the new bits.

**Comment by monperrus** [comment]
You were right, now I have `4d5f100e6f9499887a64ab6c2a0138048d6210765254eea8ed5019e2e2072aad, Date: 2023-04-25 10:42:34`.

I now see  `Properties->Receiving Options tab->Always connect with HTTP/1`.

Activated it, the log only contains HTTP/1, but it does not fix the bug.
We can exclude the HTTP2 hypothesis.

**Comment by mcrha** [comment]
I see, thank you for a quick check.

The problem is that I do have a standalone server and the Flatpak-ed Evolution can connect to it with NTLM. It's an Exchange 2019.

We ruled out the system problem (with curl, even it's OpenSSL). I see the sandbox has the `wget` as well. If even that will work, then I guess the problem is somewhere in the libsoup, but why only for you doesn't make any sense.

**Comment by monperrus** [comment]
I'm going back in time and still observe the same problem. Tried with a fresh Evolution config in flatpak, same problem. Was even able to really break GnuTLS in the host by playing with `/etc/gnutls/config`.

How to list flatpak commits before `0414db49604c08e720a5c6256c60dfcfd4dc8a500949789ec736a609018de1ca` of 2022-09-23?

**Comment by mcrha** [comment]
> How to list flatpak commits before `0414db49604c08e720a5c6256c60dfcfd4dc8a500949789ec736a609018de1ca` of 2022-09-23?

I mentioned it above, at https://github.com/flathub/org.gnome.Evolution/issues/107#issuecomment-1558810835 . Flathub does not keep all the history since the project had been added, for obvious reasons (one of them being required disk size), thus there is only one commit done before the 2022-09-23:

```
    Commit: def74e5bce7c7a789f878f9d1562acfaa431edd6ff29902525d8e37dd1b8a736
   Subject: Update to 3.44.4 (93088d3b)
      Date: 2022-08-08 17:15:08 +0000
```

Nonetheless, if you reproduce the problem also with older Evolution, then I'm afraid the problem lies elsewhere. Possibly the runtime the evolution uses. Maybe some library update causes this for you, which had been done in more SDK/runtime versions (because the Evolution usually uses different runtimes for major versions), but which one it was I cannot tell. Not mentioning that it's a similar guess as everything else I provided here, I'm sorry.

**Comment by monperrus** [comment]
My next debug step is to change the host, to see if the combination recent flatpak/my EWS server works.

**Comment by monperrus** [comment]
On the original machine, I get it to work also. Cool!

But it's very brittle. 

I have to click on "Always connect with HTTP/1" during initial account creation. If I do it after, it's not accepted: I can select it, but when I go outside of the config screen and come back it's unchecked again. So I assume it's not taken into account.

**Comment by mcrha** [comment]
> when I go outside of the config screen

What does that mean precisely, please? Do you open the account Properties, then make the change, then confirm the change with the OK button, then you open the account Properties again and the option is back with the value it was before the change you just confirmed with the OK button? I cannot reproduce it with these steps, the option change is saved and read back as expected here.

**Comment by monperrus** [comment]
> What does that mean precisely, please? Do you open the account Properties, then make the change, then confirm the change with the OK button, then you open the account Properties again and the option is back with the value it was before the change you just confirmed with the OK button?

That's correct. 

Along the same line, most of the time when I change something in the receiving options tab, the connection is lost  with some "internal server error" happening (this happened for example when I unticked "Listen for server change notifications") and I have to recreate the account config from scratch. Lots of those buggy behaviors are non entirely deterministic, I'm doing my best to give you very precise reproduction info 🙏

From an end-user perspective, it feels like the whole EWS stack has become unstable compared to 3.44.

**Comment by mcrha** [comment]
Okay, good, you are welcome. It was a long run. Knowing the HTTP/2 is the problem we could make it more quickly for sure ;)
