### ISSUE TITLE
"Look up for an EteSync account" not shown in version 3.48.1

### ISSUE THREAD

**Issue by mulles** [flathub/org.gnome.Evolution#122]
**How to reproduce:** 
Install  org.gnome.Evolution   3.48.1  from Flathub:
`flatpak install flathub org.gnome.Evolution`

From  release 3.48.0 it disappared. 
`flatpak update --commit=110c8bf8dca8105074d9ae0a6015b0d5c56865eb9b5bc7304add7fbb0e12ed0e org.gnome.Evolution`

Try to add calendar via Collection. Option "Look up for an EteSync account"  is not shown. 

**Workaround:** 

Downgrade to version 3.46.4:
` flatpak update --commit=c7253ee33e4f601ee213fa916e8cb4e8c3e2b7b4022cb8cb7072ca442af9c6da org.gnome.Evolution`
`flatpak kill org.gnome.Evolution` (to ensure downgrade gets applied)
`flatpak mask org.gnome.Evolution` (to prevent updates of the Evolution to new versions)

Option "Look up for an EteSync account" is shown and works as expected :) 

This issue might be related to #38.

Who might be able to help solving the issue @tasn. 

Please tell me if some screenshots or logs might help. And give thumbs up if the workaround did work for you.

**Comment by mcrha** [comment]
The EteSync support is taken out as an extension since https://github.com/flathub/org.gnome.Evolution/pull/108 . I do not know how it works here, should the https://github.com/flathub/org.gnome.Evolution/blob/027b3694ead4707bd6d8830f30c6aaf8cd23388a/org.gnome.Evolution.Extension.evolution-etesync.json be built & installed into a specific place?

**Comment by Sesivany** [comment]
I would also state that Etesync is a 3rd-party plugin. It has been built as part of the flatpak only because there was no way to ship it separately. None of us is using the functionality and we receive no feedback related to Etesync when we push a new release to the beta channel. That's why regressions regarding Etesync may slip into the stable release.

**Comment by mcrha** [comment]
Jiri, it looks like you'd need to create a new project for the EteSync, then it'll be built and known as an extension for the Evolution. I think so, because [the GIMP](https://github.com/flathub/org.gimp.GIMP) and ([one of](https://github.com/flathub/org.gimp.GIMP.Plugin.GMic)) its plugins are also separated into the standalone projects.

**Comment by parisni** [comment]
Hi, I also lost my etesync binding when updated flatpak. I mean no access to contacts, calendar, tasks and notes. 
1. Is there a workaround (like downgrading flatpak app) ?
2. Can this change be rollback ? (or do we really need to maintain a fork for this)

**Comment by mcrha** [comment]
You can downgrade, yes, the above-mentioned commit (in the description, under "Downgrade to version 3.46.4:" command) is fine, I could add a collection account referencing an EteSync account.

The tricky part is to restart the background processes the flatpak can have left running (on purpose, it's not a bug). Thus after downgrading do:

```
   flatpak kill org.gnome.Evolution
```

and only then start the Evolution again. Maybe the missing kill caused it not to work (as mentioned in the description)? I do not see any other reason why the EteSync could not work when returning back to the version where it worked before the upgrade.

**Comment by iavael** [comment]
@Sesivany considering this https://github.com/flathub/org.gnome.Evolution/issues/81#issuecomment-1069351636 can we assume that etesync support would be dropped since it cannot be implemented via extensions and current extension cannot be fixed?

**Comment by mulles** [comment]
> You can downgrade, yes, the above-mentioned commit (in the description, under "Downgrade to version 3.46.4:" command) is fine, I could add a collection account referencing an EteSync account.
> 
> The tricky part is to restart the background processes the flatpak can have left running (on purpose, it's not a bug). Thus after downgrading do:
> 
> ```
>    flatpak kill org.gnome.Evolution
> ```
> 
> and only then start the Evolution again. Maybe the missing kill caused it not to work (as mentioned in the description)? I do not see any other reason why the EteSync could not work when returning back to the version where it worked before the upgrade.

I updated my initial issue post with this and thus we have a working workaround.  Much appreciated @mcrha 

 @mcrha can anybody build and publish such a flatpak? If so I might find the time in the coming month learn how to build and then  support such a package. Name would be something like "Evolution with Etesync Plugin" ? @Sesivany  unfortunalety that might bloat flathub or other package repo instead of Evolution.

**Comment by mcrha** [comment]
@tasn I guess a call for you. All the files are ready (see above), just open a new flathub project, add there the file(s) and build it. What do you think?

**Comment by daftaupe** [comment]
Hello,

I'm about to open a PR to get the EteSync plugin for Evolution merged in Flathub. But they ask for the following confirmation "I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge)." and the application ID will be "org.gnome.Evolution.Extension.evolution-etesync" which I obviously don't own. Is that ok ? Will someone from here be able to confirm that it's ok once the PR is opened ?

If anyone wants to review prior to me opening the PR, please check https://github.com/daftaupe/flathub/tree/org.gnome.Evolution.Extension.evolution-etesync.

**Comment by mcrha** [comment]
I guess they want it for the app verification, right? If a "green" from my side would be enough, then I can do it. Otherwise there might be needed something from the GNOME folks.

Is it that you can create the project, it'll only not be considered [verified](https://flathub.org/cs/apps/collection/verified/1)? I mean, maybe it would work to start as an unverified app and go through the verification process afterwards. It's in the testing state at the moment anyway (the files worked properly locally, but the Flathub.org might do things slightly differently or whatever, uncovering some gaps in the assuptions in the scripts).

**Comment by Sesivany** [comment]
Is the "verified" status really necessary to open a new repo at Flathub? I don't think so and I would proceed without it. There is a manual verification process for GNOME apps, but I have no idea how it works and if it also applies to plugins.

**Comment by daftaupe** [comment]
The build has succeeded.
Is anyone able to test that the extension installs properly ? Here is the provided instruction : https://github.com/flathub/flathub/pull/4297#issuecomment-1615943208

I don't have a machine with flatpack available so I will need some time to test it.

**Comment by daftaupe** [comment]
@mulles @parisni you should now be able to use the org.gnome.Evolution.Extension.evolution-etesync extension on flathub.

**Comment by parisni** [comment]
hi @daftaupe currently running evolution `3.48.3` together w/ evolution-etesync `1.1.1`, and it works like a charm so far. Many thanks

**Comment by daftaupe** [comment]
@mulles can this be closed now ?

**Comment by mulles** [comment]
@daftaupe  thx you so much for creating see extension. Work like a charm. 

Thus I closed :)
