### ISSUE TITLE
Add write permissions for home folder

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.gnome.Evolution#13]
This is of cause closely related to #2, but this time it's about a lack of write functionality. I can't save attachments that people mail me, I can't even save them into the downloads folder.

Until this is fixed, I would recommend you to add read-write permissions to the home folder.

**Temporary workaround**
```
$ flatpak override org.gnome.Evolution --filesystem=home --user
```

**Comment by Sesivany** [comment]
What distribution are you using? This is most likely a problem in flatpak portals in your distro. Saving attachments works just fine for me on Fedora. I'm not going to open a full access to the home just because portals don't work for someone.

**Comment by Eonfge** [comment]
Should have mentioned it. I'm Using Fedora 30. Installed it last week and only found out yesterday about the attachments issue.

**Comment by Sesivany** [comment]
OK, there must be some issue with your setup... do you have xdg-desktop-portal package installed? What environment do you use? When you try to open the attachment directly do you get a dialog that gives you a choice of apps where to open it?

**Comment by Eonfge** [comment]
- xdg-desktop-portal is installed
- GNOME 3.32, default Fedora 30 Workstation

Found the difference. I have multiple attachments and I try to do **Save All**

Then, I get a file browser without /Home/ access. If I do the same with just one file, I do get access to my documents and all other XDG folders.

**Comment by Sesivany** [comment]
Yes, I can reproduce this as well. Let's see if it's a limitation of the flatpak portal (not being able to work with multiple files at once) or Evolution not using the right GTK method on that button.

**Comment by Sesivany** [comment]
It's indeed a limitation of the portal: "Save All": (evolution.bin:54): Gtk-WARNING **: 10:39:39.691: GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER is not supported by GtkFileChooserNativePortal

The portal developers say it'd be really difficult to safely expose the whole directory, so they're not planning to implement it.
We've made quite some effort to sandbox Evolution and we don't want to undo that just because of this feature. At least for the time being we will hide the "Save All" button in flatpak builds: https://gitlab.gnome.org/GNOME/evolution/commit/eee405f8841c0d58edb57663f8ed770d8ca38259
