### ISSUE TITLE
No access to home directory

### ISSUE THREAD

**Issue by mczimmermann** [flathub/org.gnome.Evolution#2]
I wanted to restore the backup from my older evolution installation, but could not access my home directory where it was stored.

Fixed it for me by manually giving evolution access. Everything else is working great so far!

**Comment by ahayzen** [comment]
Evolution should really be using the filechooser portal for these, as then no filesystem access need to be given. I'm surprised it doesn't work now, is Evolution not using a GtkFileChooserNative for those pickers ?

**Comment by mczimmermann** [comment]
I have double checked it and my home directory is empty when I try to open a file (add attachment, restore backup) in evolution.

**Comment by nedrichards** [comment]
@ahayzen a code search shows no results for FileChooserNative (and a lot for FileChooser) so it seems not!

I've upstreamed this issue as https://gitlab.gnome.org/GNOME/evolution/issues/165

**Comment by ahayzen** [comment]
@nedrichards as stated here https://gitlab.gnome.org/GNOME/evolution/issues/165#note_376019 this commit to the master branch adds portal support https://gitlab.gnome.org/GNOME/evolution/commit/6cde71f954547bd05e36b08757b92735742f9da6 .  Could this be backported/patched in the flatpak as it is not going into the 3.30 series due to the string freeze but currently applies cleanly ?  I think it is worth carrying the patch until 3.32 if Evolution is then able to drop `--filesystem=home` :-)

**Comment by ahayzen** [comment]
Also assume that https://gitlab.gnome.org/GNOME/evolution-data-server/commit/ad4380f1cbb8a07b476692d4b0519901214f0211 (3.30 series)  or https://gitlab.gnome.org/GNOME/evolution-data-server/commit/ff6ae6b89798ee6d651535cc238db889bea7d2e4 (master) is required for this to work ?

**Comment by Sesivany** [comment]
Yes, I will introduce the patch and drop --filesystem=home with the update to 30.3 next week.
